import { useState } from "react";
import logo from "../assets/logo.png";

const menuItems = [
	{ id: "plan", icon: "▥", label: "Mi Plan" },
	{ id: "facturas", icon: "▤", label: "Mis Facturas", badge: true },
	{ id: "pago", icon: "▣", label: "Pagar Factura" },
	{ id: "paz", icon: "♢", label: "Paz y Salvo" },
	{ id: "soporte", icon: "⚒", label: "Soporte / Fallas" },
];

function StatusPill({ children = "Servicio activo" }) {
	return <span className="client-status"><i />{children}</span>;
}

function ClientSidebar({ currentView, setCurrentView }) {
	return (
		<aside className="client-sidebar">
			<div className="client-logo-wrap"><img src={logo} alt="Global Conexit" /></div>
			<div className="client-profile"><span className="profile-avatar">CA</span><div><strong>Carlos Andrés</strong><small>1.032.456.789</small></div><span className="profile-plan"><i />Plan Familiar 300 Mbps</span></div>
			<nav className="client-nav" aria-label="Navegación del portal">{menuItems.map((item) => <button className={currentView === item.id ? "active" : ""} key={item.id} onClick={() => setCurrentView(item.id)}><span className="nav-icon">{item.icon}</span>{item.label}{item.badge && <b />}</button>)}</nav>
			<button className="client-logout" onClick={() => setCurrentView("plan")}><span>⇥</span>Cerrar sesión</button>
		</aside>
	);
}

function ClientHeader({ title, subtitle }) { return <header className="client-header"><div><h1>{title}</h1><p>{subtitle}</p></div><StatusPill /></header>; }
function Metric({ icon, label, value, unit, accent = "" }) { return <div className="metric-card"><span className={`metric-icon ${accent}`}>{icon}</span><small>{label}</small><strong className={accent}>{value}<em>{unit}</em></strong></div>; }
function Usage({ label, value, width, upload }) { return <div className="usage-row"><div><span>{label}</span><strong>{value}</strong></div><div className="usage-track"><span className={upload ? "upload" : ""} style={{ width }} /></div></div>; }
function Info({ label, value }) { return <div><small>{label}</small><strong>{value}</strong></div>; }
function ServiceStatus() { return <section className="dashboard-card service-card"><h3>Estado del servicio</h3>{["Conectividad a internet", "Resolución DNS", "Router / CPE", "Red de fibra óptica"].map((item, index) => <div className="service-row" key={item}><span>{item}</span><strong><i />{index === 2 ? "Conectado" : index === 3 ? "Operativa" : "Normal"}</strong></div>)}<p className="helper-text">◷ Última actualización: hoy, 02 Sep 2026 — 10:38 a.m.</p></section>; }

function PlanView() {
	return <><ClientHeader title="Mi Plan" subtitle="Resumen de tu servicio y métricas en tiempo real" /><section className="plan-hero"><div className="plan-hero-top"><div><span className="eyebrow-light">TU PLAN ACTIVO</span><h2>Plan Familiar — 300 Mbps</h2><p>Contrato #GC-2022-004891 · Cliente desde Marzo 2022</p></div><StatusPill>Activo</StatusPill></div><div className="billing-line"><span>Ciclo de facturación</span><strong>3 Sep — 3 Oct 2026 · 29 días restantes</strong></div><div className="progress-track"><span /></div><div className="plan-summary"><div><small>Velocidad Bajada</small><strong>300 Mbps</strong></div><div><small>Velocidad Subida</small><strong>150 Mbps</strong></div><div><small>Próxima renovación</small><strong>3 Oct 2026</strong></div><div><small>Dirección</small><strong>Cra. 45 #92-18, Bogotá D.C.</strong></div></div></section><div className="metric-grid"><Metric icon="⇣" label="VELOCIDAD DESCARGA" value="296" unit="Mbps" accent="orange" /><Metric icon="⇡" label="VELOCIDAD SUBIDA" value="143" unit="Mbps" accent="orange" /><Metric icon="◷" label="LATENCIA" value="4" unit="ms" /><Metric icon="✓" label="UPTIME" value="99.9" unit="%" accent="gold" /></div><div className="dashboard-grid"><section className="dashboard-card consumption-card"><div className="card-heading"><h3>Consumo del ciclo</h3><span className="soft-badge">Sin límite</span></div><Usage label="↓ Descargado" value="487.3 GB" width="67%" /><Usage label="↑ Subido" value="124.8 GB" width="29%" upload /><p className="helper-text">Período: 3 Sep – 3 Oct 2026 · 4 días transcurridos</p></section><ServiceStatus /></div><section className="dashboard-card equipment-card"><h3>Información del equipo</h3><div className="equipment-grid"><Info label="Router asignado" value="TP-Link Archer AX53" /><Info label="Dirección MAC" value="A4:2B:8C:11:3E:07" /><Info label="IP asignada" value="181.132.44.209" /><Info label="Tipo de conexión" value="Fibra óptica GPON" /></div></section></>;
}

function InvoicesView({ setCurrentView }) { return <><ClientHeader title="Mis Facturas" subtitle="Historial de facturación y pagos" /><div className="invoice-metrics"><Info label="VALOR MENSUAL" value="$ 49.990" /><Info label="PENDIENTE DE PAGO" value="$ 49.990" /><Info label="TOTAL PAGADO (2026)" value="$ 249.950" /></div><section className="dashboard-card invoices-card"><div className="tabs"><button className="selected">Todas</button><button>Pendientes</button><button>Pagadas</button></div><div className="invoice-head"><span>REFERENCIA</span><span>PERÍODO</span><span>VALOR</span><span>ESTADO</span><span>ACCIONES</span></div>{["Septiembre 2026", "Agosto 2026", "Julio 2026", "Junio 2026", "Mayo 2026", "Abril 2026"].map((period, index) => <div className="invoice-row" key={period}><strong>FC-2026-{String(9 - index).padStart(3, "0")}</strong><span>{period}<small>{index ? `Pagada el ${index + 1} Sep 2026` : "Vence 5 Oct 2026"}</small></span><strong>$ 49.990</strong><span className={`invoice-status ${index ? "paid" : "pending"}`}>{index ? "✓ Pagada" : "⌛ Pendiente"}</span><span><button className="pdf-button">⇩ PDF</button>{!index && <button className="pay-button" onClick={() => setCurrentView("pago")}>Pagar</button>}</span></div>)}</section></>; }

function PaymentView() { return <><ClientHeader title="Pagar Factura" subtitle="Realiza el pago de tu factura pendiente" /><section className="payment-layout"><div className="payment-due"><div><small>Factura a pagar</small><strong>Septiembre 2026</strong><span>FC-2026-009 · Vence 5 Oct 2026</span></div><b>$ 49.990<small>COP · IVA incluido</small></b></div><div className="dashboard-card payment-card"><h3>Método de pago</h3><div className="payment-methods"><button className="selected">▣ <strong>Tarjeta</strong><small>Débito o crédito</small></button><button>▥ <strong>PSE</strong><small>Débito bancario</small></button></div><label>NÚMERO DE TARJETA<input placeholder="1234  5678  9012  3456" /></label><div className="input-row"><label>VENCIMIENTO<input placeholder="MM/AA" /></label><label>CVV<input placeholder="•••" /></label></div><label>NOMBRE EN LA TARJETA<input placeholder="Como aparece en la tarjeta" /></label><button className="submit-button">Pagar $ 49.990</button><p className="helper-text center">🔒 Pago cifrado con SSL 256-bit · Procesado por Redeban</p></div></section></>; }

function SupportView() { return <><ClientHeader title="Soporte / Fallas" subtitle="Reporta problemas y sigue tus tickets" /><div className="support-grid"><section className="dashboard-card support-form"><h2>Reportar nueva falla</h2><p>Describe el problema y un técnico se comunicará contigo a la brevedad.</p><label>TIPO DE FALLA *<select defaultValue=""><option value="" disabled>Selecciona el tipo de falla...</option><option>Intermitencia de conexión</option><option>Velocidad reducida</option></select></label><label>PRIORIDAD<div className="priority"><button>Baja</button><button className="selected">Media</button><button>Alta</button></div></label><label>DESCRIPCIÓN DEL PROBLEMA *<textarea placeholder="Describe detalladamente el problema: ¿desde cuándo ocurre?, ¿a qué horas?, ¿afecta a todos los dispositivos?..." /></label><label>TELÉFONO DE CONTACTO<input value="310 456 7890" readOnly /></label><button className="submit-button">Crear ticket de soporte</button></section><section className="dashboard-card tickets"><h2>Mis tickets</h2>{["Velocidad por debajo del plan", "Intermitencia de conexión"].map((ticket, index) => <article key={ticket}><small>TK-2026-0{index ? "28" : "41"}</small><strong>{ticket}</strong><p>{index ? "La conexión cae varias veces al día especialmente entre las 7-9 pm." : "Velocidad medida por debajo de los 200 Mbps prometidos en horas pico."}</p><span>Resuelto</span><time>{index ? "3 Jun 2026" : "14 Ago 2026"}</time></article>)}</section></div></>; }

function CertificateView() { return <><ClientHeader title="Paz y Salvo" subtitle="Certificado de no adeudo con Global Conexit" /><section className="certificate dashboard-card"><div className="certificate-title"><h2>CERTIFICADO DE PAZ Y SALVO</h2><p>Global Conexit S.A.S. · NIT 900.123.456-7</p></div><p>Por medio del presente documento, <strong>Global Conexit S.A.S.</strong>, identificada con NIT 900.123.456-7, certifica que el(la) señor(a):</p><div className="certificate-data"><Info label="Nombre completo" value="Carlos Andrés Rodríguez" /><Info label="Documento de identidad" value="CC 1.032.456.789" /><Info label="Contrato" value="#GC-2022-004891" /><Info label="Servicio" value="Plan Familiar — 300 Mbps" /><Info label="Dirección del servicio" value="Cra. 45 #92-18, Bogotá D.C." /></div><p>Se encuentra <strong className="green">a PAZ Y SALVO</strong> con todas sus obligaciones económicas con esta empresa a la fecha de expedición de este documento.</p><div className="certificate-dates"><Info label="Fecha de expedición" value="02 de Septiembre de 2026" /><Info label="Válido hasta" value="02 de Octubre de 2026" /></div><small className="helper-text">Este certificado es de carácter informativo y tiene validez de 30 días calendario a partir de su expedición.</small><div className="certificate-actions"><button className="submit-button">⇩ Descargar PDF</button><button className="secondary-button">▣ Imprimir</button></div></section></>; }

function ClientPortal() { const [currentView, setCurrentView] = useState("plan"); const content = { plan: <PlanView />, facturas: <InvoicesView setCurrentView={setCurrentView} />, pago: <PaymentView />, paz: <CertificateView />, soporte: <SupportView /> }; return <div className="client-portal"><ClientSidebar currentView={currentView} setCurrentView={setCurrentView} /><main className="client-main">{content[currentView]}</main></div>; }

export default ClientPortal;
